{{- if .Values.deployments.etcdOperator }}
apiVersion: etcd.database.coreos.com/v1beta2
kind: EtcdCluster
metadata:
  name: "{{ .Values.etcdCluster.name }}"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "etcd-operator.name" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    {{- if .Values.clusterwide.enabled }}
    "etcd.database.coreos.com/scope": "clusterwide"
    {{- end }}
spec:
  size: {{ .Values.etcdCluster.size }}
  version: "{{ .Values.etcdCluster.version }}"
  pod:
    antiAffinity: {{ .Values.etcdCluster.pod.antiAffinity }}
    {{- if .Values.etcdCluster.pod.nodeSelector }}  
    nodeSelector: {{ toYaml .Values.etcdCluster.pod.nodeSelector }}
    {{- end }}
    {{- if .Values.etcdCluster.pod.resources }}  
    resources: 
{{ toYaml .Values.etcdCluster.pod.resources | indent 6 }}
    {{- end }}
    {{- if .Values.etcdCluster.enablePVC }}  
    persistentVolumeClaimSpec:
      storageClassName: {{ .Values.etcdCluster.pvc.storageClassName }}
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.etcdCluster.pvc.size }}
    {{- end }}
  {{- if .Values.etcdCluster.enableTLS }}
  TLS:
{{ toYaml .Values.etcdCluster.tls | indent 4 }}
  {{- end }}
{{- end }}
